# XcodeGen Project Specification
# Run: xcodegen generate
# Install: brew install xcodegen

name: DCAVisualizer
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: NO
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      SWIFT_OPTIMIZATION_LEVEL: -O

packages:
  DCAKit:
    path: ./DCAKit
  StockHistoryAPI:
    path: ./StockHistoryAPI

targets:
  DCAVisualizer:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: DCAKit
      - package: StockHistoryAPI
    settings:
      base:
        INFOPLIST_FILE: App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.dcavisualizer
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"  # iPhone and iPad
        SUPPORTS_MACCATALYST: NO
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: DCA Visualizer
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  DCAKitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DCAKit/Tests/DCAKitTests
    dependencies:
      - package: DCAKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.dcakit.tests
        GENERATE_INFOPLIST_FILE: YES

  StockHistoryAPITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: StockHistoryAPI/Tests/StockHistoryAPITests
    dependencies:
      - package: StockHistoryAPI
      - package: DCAKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.stockhistoryapi.tests
        GENERATE_INFOPLIST_FILE: YES

  DCAVisualizerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/DCAVisualizerTests
    dependencies:
      - target: DCAVisualizer
      - package: StockHistoryAPI
      - package: DCAKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.dcavisualizer.tests
        GENERATE_INFOPLIST_FILE: YES

  DCAVisualizerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/DCAVisualizerUITests
    dependencies:
      - target: DCAVisualizer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.dcavisualizer.uitests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  DCAVisualizer:
    build:
      targets:
        DCAVisualizer: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - DCAKitTests
        - StockHistoryAPITests
        - DCAVisualizerTests
        - DCAVisualizerUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
